import { Course } from "./types";

export const MOCK_COURSES: Course[] = [
    {
        id: 1,
        title: "Full-Stack Web Development with Next.js 15",
        description:
            "Build production-ready web apps with React, Next.js, TypeScript, and modern tooling. Covers SSR, API routes, auth, and deployment.",
        category: "Web Development",
        level: "Intermediate",
        status: "Published",
        students: 3842,
        rating: 4.9,
        reviews: 621,
        duration: "48h 30m",
        lessons: 112,
        revenue: 57630,
        thumbnail: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&q=80",
        lastUpdated: "Mar 28, 2026",
        completionRate: 74,
    },
    {
        id: 2,
        title: "UI/UX Design Masterclass: From Zero to Pro",
        description:
            "Learn Figma, design systems, user research, prototyping, and how to hand off to developers like a professional.",
        category: "Design",
        level: "Beginner",
        status: "Published",
        students: 2156,
        rating: 4.8,
        reviews: 389,
        duration: "32h 15m",
        lessons: 78,
        revenue: 32340,
        thumbnail: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&q=80",
        lastUpdated: "Mar 15, 2026",
        completionRate: 68,
    },
    {
        id: 3,
        title: "Advanced TypeScript Patterns & Architecture",
        description:
            "Deep dive into generics, utility types, decorators, module patterns, and building scalable TypeScript applications.",
        category: "Programming",
        level: "Advanced",
        status: "Published",
        students: 1089,
        rating: 4.7,
        reviews: 204,
        duration: "26h 45m",
        lessons: 64,
        revenue: 21780,
        thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&q=80",
        lastUpdated: "Feb 20, 2026",
        completionRate: 61,
    },
    {
        id: 4,
        title: "Machine Learning Fundamentals with Python",
        description:
            "Hands-on introduction to ML algorithms, scikit-learn, data preprocessing, and model evaluation techniques.",
        category: "Data Science",
        level: "Intermediate",
        status: "Under Review",
        students: 0,
        rating: 0,
        reviews: 0,
        duration: "39h 00m",
        lessons: 91,
        revenue: 0,
        thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80",
        lastUpdated: "Apr 1, 2026",
        completionRate: 0,
    },
    {
        id: 5,
        title: "Docker & Kubernetes: Container Orchestration",
        description:
            "Master containerization, write production Dockerfiles, set up Kubernetes clusters, and deploy scalable microservices.",
        category: "DevOps",
        level: "Advanced",
        status: "Draft",
        students: 0,
        rating: 0,
        reviews: 0,
        duration: "22h 10m",
        lessons: 53,
        revenue: 0,
        thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&q=80",
        lastUpdated: "Mar 30, 2026",
        completionRate: 0,
    },
    {
        id: 6,
        title: "React Native: Build iOS & Android Apps",
        description:
            "Create cross-platform mobile applications with React Native, Expo, native APIs, animations, and app store publishing.",
        category: "Mobile",
        level: "Intermediate",
        status: "Published",
        students: 897,
        rating: 4.6,
        reviews: 143,
        duration: "29h 20m",
        lessons: 70,
        revenue: 13455,
        thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&q=80",
        lastUpdated: "Feb 12, 2026",
        completionRate: 55,
    },
];
